version: '3.8'

services:
  web:
    build: .
    expose:
      - "5000"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-your-super-secret-key}
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/app_db
      - HOST_URL=${HOST_URL:-http://localhost}
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./uploads:/app/uploads:ro
      - ./app/static:/app/app/static:ro
    depends_on:
      - web
    restart: unless-stopped

volumes:
  app_uploads:
  postgres_data: 